[conversation.tools.cargo_check]
enable = false
run = "unattended"
source = "local"
command = "just serve-tools {{context}} {{tool}}"
description = "Run `cargo check` for the given package, validating if the code compiles."

[conversation.tools.cargo_check.style]
inline_results = "full"
results_file_link = "off"
parameters = "function_call"

[conversation.tools.cargo_check.parameters.package]
description = "Package to run check for, if unspecified, all workspace packages will be checked."
type = "string"
