[conversation.tools.cargo_test]
enable = false
run = "unattended"
source = "local"
command = "just serve-tools {{context}} {{tool}}"
description = "Execute all unit and integration tests and build examples of the project."

[conversation.tools.cargo_test.style]
inline_results = "full"
results_file_link = "off"
parameters = "function_call"

[conversation.tools.cargo_test.parameters.package]
description = "Package to run tests for, if unspecified, all workspace packages will be tested."
type = "string"

[conversation.tools.cargo_test.parameters.testname]
description = "If specified, only run tests containing this string in their names."
type = "string"
