disallowed-macros = []
disallowed-methods = []
disallowed-types = []

too-many-arguments-threshold = 10
allow-unwrap-in-tests = true
allow-print-in-tests = true
allowed-duplicate-crates = [
    "windows-link",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
]
# check-private-items = true
