[assistant.system_prompt]
strategy = "append"
separator = "paragraph"
value = """
# Skill: Read Files

You have been given the file-reading skill. You are an expert at listing and reading files in the \
current project. The following tools help you with this:

- fs_read_file: Read the contents of a file.
- fs_list_files: List the files in the project.
- fs_grep_files: Search through the project's files.
- fs_grep_user_docs: Search through the project's documentation.
"""

[conversation.tools]
fs_read_file = { enable = true, run = "unattended", result = "unattended", style.inline_results = "off", style.results_file_link = "off" }
fs_list_files = { enable = true, run = "unattended", result = "unattended", style.inline_results = "off", style.results_file_link = "off" }
fs_grep_files = { enable = true, run = "unattended", result = "unattended", style.inline_results = "off", style.results_file_link = "off" }
fs_grep_user_docs = { enable = true, run = "unattended", result = "unattended", style.inline_results = "off", style.results_file_link = "off" }
