[conversation.tools.github_read_file]
enable = false
source = "local"
command = "just serve-tools {{context}} {{tool}}"
description = """
Fetch the contents of one or more files
"""

[conversation.tools.github_read_file.parameters.repository]
type = "string"
description = """
Repository to search for code.

If unspecified, it defaults to the current project's GitHub repository.
"""

[conversation.tools.github_read_file.parameters.path]
type = "string"
required = true
description = '''
File path to get contents of.
'''

[conversation.tools.github_read_file.parameters.ref]
type = "string"
description = '''
The name of the commit/branch/tag.

If unspecified, it defaults to the repositoryâ€™s default branch (usually `main`)
'''
