[conversation.tools.fs_create_file]
enable = false
source = "local"
command = "just serve-tools {{context}} {{tool}}"
description = """
Create a new file in the project's local filesystem.
"""

[conversation.tools.fs_create_file.style]
parameters = "just serve-tools {{context}} {{tool}}"
inline_results = "off"
results_file_link = "off"

[conversation.tools.fs_create_file.parameters.path]
type = "string"
required = true
description = """
The path to the file to create. The path must be relative to the project's root.
"""

[conversation.tools.fs_create_file.parameters.content]
type = "string"
required = false
description = """
The content of the file to create. If not specified, the file will be empty.
"""
