[conversation.tools.fs_grep_user_docs]
enable = false
run = "unattended"
style.inline_results = "off"

source = "local"
command = "just serve-tools {{context}} {{tool}}"
description = "Grep the project's user documentation."

[conversation.tools.fs_grep_user_docs.parameters.pattern]
type = "string"
required = true
description = """
Regular expression to filter the results by.
"""

[conversation.tools.fs_grep_user_docs.parameters.return_entire_file]
type = "boolean"
default = false
description = """
Whether to return the entire file contents.

If enabled, the tool will return the entire file contents of any files matching
the pattern. If disabled (the default), only the matching lines and 5 contextual
lines above and below the matching lines will be returned.
"""
