[conversation.tools.fs_list_files]
enable = false
run = "unattended"
style.inline_results = "off"

source = "local"
command = "just serve-tools {{context}} {{tool}}"
description = "List files in the project's local filesystem."

[conversation.tools.fs_list_files.parameters.prefixes]
type = "array"
items.type = "string"
description = """
Optional list of path prefixes to filter the results by.

If unspecified, all files in the project will be returned.
"""

[conversation.tools.fs_list_files.parameters.extensions]
type = "array"
items.type = "string"
description = """
Optional list of file extensions to filter the results by.

If unspecified, all extensions will be returned.
"""
