[conversation.tools.fs_read_file]
enable = false
run = "unattended"
style.inline_results = "off"

source = "local"
command = "just serve-tools {{context}} {{tool}}"
description = """
Read the contents of a file in the project's local filesystem.

You can use `fs_grep_files` to search for specific patterns in the file
contents, before reading the entire contents of a specific file using this tool.
"""

[conversation.tools.fs_read_file.parameters.path]
type = "string"
required = true
description = """
The path to the file to read.
"""

[conversation.tools.fs_read_file.parameters.start_line]
type = "integer"
description = """
The line number to start reading from.
"""

[conversation.tools.fs_read_file.parameters.end_line]
type = "integer"
description = """
The line number to stop reading at.
"""
