[package]
name = "jp_workspace"

authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
jp_config = { workspace = true }
jp_conversation = { workspace = true }
jp_id = { workspace = true }
jp_storage = { workspace = true }
jp_tombmap = { workspace = true }

ahash = { workspace = true }
directories = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
test-log = { workspace = true }

[lints]
workspace = true
